# Tim Ruebenach – 95 Claude Skills Bundle
# Paperclip batch import – paste raw URL into Skills > Add

https://github.com/timruebenach/claude-skills/tree/main/skills/brand-guidelines
https://github.com/timruebenach/claude-skills/tree/main/skills/canvas-design
https://github.com/timruebenach/claude-skills/tree/main/skills/deep-research
https://github.com/timruebenach/claude-skills/tree/main/skills/defuddle
https://github.com/timruebenach/claude-skills/tree/main/skills/doc-coauthoring
https://github.com/timruebenach/claude-skills/tree/main/skills/frontend-design
https://github.com/timruebenach/claude-skills/tree/main/skills/gstack
https://github.com/timruebenach/claude-skills/tree/main/skills/json-canvas
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-ab-test-setup
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-ad-creative
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-ai-seo
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-analytics-tracking
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-aso-audit
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-churn-prevention
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-cold-email
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-community-marketing
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-competitor-alternatives
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-competitor-profiling
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-content-strategy
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-copy-editing
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-copywriting
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-customer-research
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-directory-submissions
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-email-sequence
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-form-cro
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-free-tool-strategy
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-image
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-launch-strategy
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-lead-magnets
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-marketing-ideas
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-marketing-psychology
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-onboarding-cro
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-page-cro
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-paid-ads
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-paywall-upgrade-cro
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-popup-cro
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-pricing-strategy
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-product-marketing-context
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-programmatic-seo
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-referral-program
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-revops
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-sales-enablement
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-schema-markup
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-seo-audit
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-signup-flow-cro
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-site-architecture
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-social-content
https://github.com/timruebenach/claude-skills/tree/main/skills/marketing-video
https://github.com/timruebenach/claude-skills/tree/main/skills/mem0
https://github.com/timruebenach/claude-skills/tree/main/skills/obsidian-bases
https://github.com/timruebenach/claude-skills/tree/main/skills/obsidian-cli
https://github.com/timruebenach/claude-skills/tree/main/skills/obsidian-markdown
https://github.com/timruebenach/claude-skills/tree/main/skills/pdf
https://github.com/timruebenach/claude-skills/tree/main/skills/pptx
https://github.com/timruebenach/claude-skills/tree/main/skills/seo
https://github.com/timruebenach/claude-skills/tree/main/skills/seo-audit
https://github.com/timruebenach/claude-skills/tree/main/skills/seo-backlinks
https://github.com/timruebenach/claude-skills/tree/main/skills/seo-cluster
https://github.com/timruebenach/claude-skills/tree/main/skills/seo-competitor-pages
https://github.com/timruebenach/claude-skills/tree/main/skills/seo-content
https://github.com/timruebenach/claude-skills/tree/main/skills/seo-dataforseo
https://github.com/timruebenach/claude-skills/tree/main/skills/seo-drift
https://github.com/timruebenach/claude-skills/tree/main/skills/seo-ecommerce
https://github.com/timruebenach/claude-skills/tree/main/skills/seo-flow
https://github.com/timruebenach/claude-skills/tree/main/skills/seo-geo
https://github.com/timruebenach/claude-skills/tree/main/skills/seo-google
https://github.com/timruebenach/claude-skills/tree/main/skills/seo-hreflang
https://github.com/timruebenach/claude-skills/tree/main/skills/seo-image-gen
https://github.com/timruebenach/claude-skills/tree/main/skills/seo-images
https://github.com/timruebenach/claude-skills/tree/main/skills/seo-local
https://github.com/timruebenach/claude-skills/tree/main/skills/seo-maps
https://github.com/timruebenach/claude-skills/tree/main/skills/seo-page
https://github.com/timruebenach/claude-skills/tree/main/skills/seo-plan
https://github.com/timruebenach/claude-skills/tree/main/skills/seo-programmatic
https://github.com/timruebenach/claude-skills/tree/main/skills/seo-schema
https://github.com/timruebenach/claude-skills/tree/main/skills/seo-sitemap
https://github.com/timruebenach/claude-skills/tree/main/skills/seo-sxo
https://github.com/timruebenach/claude-skills/tree/main/skills/seo-technical
https://github.com/timruebenach/claude-skills/tree/main/skills/skill-creator
https://github.com/timruebenach/claude-skills/tree/main/skills/superpowers-brainstorming
https://github.com/timruebenach/claude-skills/tree/main/skills/superpowers-dispatching-parallel-agents
https://github.com/timruebenach/claude-skills/tree/main/skills/superpowers-executing-plans
https://github.com/timruebenach/claude-skills/tree/main/skills/superpowers-finishing-a-development-branch
https://github.com/timruebenach/claude-skills/tree/main/skills/superpowers-receiving-code-review
https://github.com/timruebenach/claude-skills/tree/main/skills/superpowers-requesting-code-review
https://github.com/timruebenach/claude-skills/tree/main/skills/superpowers-subagent-driven-development
https://github.com/timruebenach/claude-skills/tree/main/skills/superpowers-systematic-debugging
https://github.com/timruebenach/claude-skills/tree/main/skills/superpowers-test-driven-development
https://github.com/timruebenach/claude-skills/tree/main/skills/superpowers-using-git-worktrees
https://github.com/timruebenach/claude-skills/tree/main/skills/superpowers-using-superpowers
https://github.com/timruebenach/claude-skills/tree/main/skills/superpowers-verification-before-completion
https://github.com/timruebenach/claude-skills/tree/main/skills/superpowers-writing-plans
https://github.com/timruebenach/claude-skills/tree/main/skills/superpowers-writing-skills
https://github.com/timruebenach/claude-skills/tree/main/skills/web-artifacts-builder
https://github.com/timruebenach/claude-skills/tree/main/skills/xlsx